### PR TITLE
Fix approve registration application response.

### PR DESCRIPTION
**Pull request by dessalines**
This fixes the response type for approving registration applications.

Ping me in some way when you can deploy a new release.

### CODE REVIEW

**Comment by MV-GH** [comment]
This will then also need to be changed in my openapi spec, this file generated based on that spec

**Comment by dessalines** [comment]
Ah my bad. When you get some time, add these contribution instructions to the readme or CONTRIBUTING.md

**Review by MV-GH — CHANGES_REQUESTED** [review]
Can you also bump the patch version?

it should be located in a gradle properties file

**Comment by MV-GH** [comment]
I have updated the openapi spec, i'll merge this now, It doesn't allow me to commit to this PR, So ill bump it in a separate PR.

**Review by MV-GH — APPROVED** [review]

**Comment by MV-GH** [comment]
The runner got stuck opened #30

**Pull request closed without merging**
